"""AI explainer — grounded natural-language explanations via DeepSeek API."""

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import requests

from drugforge.config import (
    DEEPSEEK_API_URL,
    DEEPSEEK_MODEL,
    DEEPSEEK_TIMEOUT,
    DISEASE_FACTS_DIR,
)

logger = logging.getLogger(__name__)

_DISCLAIMER = (
    "This explanation is generated by an AI model using only the computed data "
    "shown above. It is a computational prediction, not clinical evidence. "
    "Laboratory validation is required before drawing any conclusions."
)

SYSTEM_PROMPT = """You are a scientific communication assistant for DrugForge, a virtual screening platform. You explain molecular docking results in plain language for researchers.

RULES:
- Use ONLY the data provided in the context below. Do not cite external sources.
- If information is missing, say "not enough data to assess this."
- Never claim a molecule "cures", "works", or "is effective." Use: "predicted", "suggests", "in silico estimate", "computational prediction."
- Keep language accessible but scientifically accurate.
- Be concise (2-3 paragraphs max).
- End with a one-sentence scope reminder.
"""

USER_PROMPT_TEMPLATE = """Explain this docking result for a researcher:

MOLECULE: {smiles} ({compound_name})
TARGET: {target_name} ({disease}) — PDB: {pdb_id}
REFERENCE DRUG: {reference_name}

SCORES:
- Vina affinity: {affinity} kcal/mol (reference: {ref_affinity})
- Vinardo score: {vinardo} kcal/mol
- Consensus score: {consensus} (1.0 = equal to reference)
- Verdict: {verdict}

DRUG-LIKENESS:
- MW: {mw}, logP: {logp}, HBD: {hbd}, HBA: {hba}
- TPSA: {tpsa}, Rotatable bonds: {rotbonds}
- Lipinski violations: {lipinski_violations}

ADMET:
- ESOL logS: {esol}, GI absorption: {gi}
- PAINS alerts: {pains}
- Hit status: {hit_status}

DISEASE CONTEXT:
{disease_facts}

Explain what this result means, whether this molecule looks promising compared to {reference_name}, and what the key strengths/weaknesses are. Be honest about limitations."""


@dataclass
class Explanation:
    """AI-generated explanation of a docking result."""
    text: str = ""
    status: str = "unavailable"  # "success" | "unavailable" | "error"
    error_detail: Optional[str] = None
    disclaimer: str = field(default=_DISCLAIMER)

    def to_dict(self) -> dict:
        return {
            "text": self.text,
            "status": self.status,
            "error_detail": self.error_detail,
            "disclaimer": self.disclaimer,
        }


def is_explainer_available() -> bool:
    """Check if DEEPSEEK_API_KEY is configured."""
    key = os.environ.get("DEEPSEEK_API_KEY", "").strip()
    return len(key) > 0


def load_disease_facts(target_id: str) -> str:
    """Load the disease fact sheet for a given target."""
    fact_path = DISEASE_FACTS_DIR / f"{target_id}.md"
    if fact_path.exists():
        return fact_path.read_text(encoding="utf-8")
    return "No disease fact sheet available for this target."


def build_prompt(result: dict, disease_facts: str) -> str:
    """
    Build the user prompt with real computed numbers from the result.

    Args:
        result: dict from PipelineResult.to_dict() or store.get_result()
        disease_facts: loaded fact sheet text

    Returns:
        Formatted prompt string with actual values.
    """
    dl = result.get("drug_likeness", {})
    admet = result.get("admet", {})
    comparisons = result.get("comparisons", [])

    # Find reference affinity from comparisons
    ref_affinity = "N/A"
    for comp in comparisons:
        if isinstance(comp, dict) and comp.get("metric") == "affinity":
            ref_affinity = comp.get("reference_value", "N/A")
            break

    pains = admet.get("pains_alerts", [])
    pains_str = ", ".join(pains) if pains else "None"

    return USER_PROMPT_TEMPLATE.format(
        smiles=result.get("molecule_smiles", "unknown"),
        compound_name=result.get("molecule_smiles", "unknown"),
        target_name=result.get("target_id", "unknown"),
        disease="malaria",  # TODO: get from target registry
        pdb_id="1J3I",  # TODO: get from target registry
        reference_name="pyrimethamine",  # TODO: get from target registry
        affinity=result.get("affinity_kcal_mol", "N/A"),
        ref_affinity=ref_affinity,
        vinardo=result.get("vinardo_score", "N/A"),
        consensus=result.get("consensus_score", "N/A"),
        verdict=result.get("verdict", "N/A"),
        mw=dl.get("molecular_weight", "N/A"),
        logp=dl.get("logp", "N/A"),
        hbd=dl.get("hbd", "N/A"),
        hba=dl.get("hba", "N/A"),
        tpsa=dl.get("tpsa", "N/A"),
        rotbonds=dl.get("rotatable_bonds", "N/A"),
        lipinski_violations=dl.get("lipinski_violations", "N/A"),
        esol=admet.get("esol_logs", "N/A"),
        gi=admet.get("gi_absorption", "N/A"),
        pains=pains_str,
        hit_status="HIT" if result.get("is_hit") else "FILTERED",
        disease_facts=disease_facts,
    )


def generate_explanation(result: dict, target_id: str) -> Explanation:
    """
    Generate a grounded natural-language explanation.

    Calls DeepSeek API with real computed data + disease fact sheet.
    Returns Explanation with status, never raises.
    """
    api_key = os.environ.get("DEEPSEEK_API_KEY", "").strip()
    if not api_key:
        return Explanation(
            status="unavailable",
            error_detail="DEEPSEEK_API_KEY not set",
        )

    try:
        disease_facts = load_disease_facts(target_id)
        prompt = build_prompt(result, disease_facts)

        payload = {
            "model": DEEPSEEK_MODEL,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            "max_tokens": 300,
            "temperature": 0.3,
        }

        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }

        resp = requests.post(
            DEEPSEEK_API_URL,
            json=payload,
            headers=headers,
            timeout=DEEPSEEK_TIMEOUT,
        )

        if resp.status_code != 200:
            return Explanation(
                status="error",
                error_detail=f"API returned {resp.status_code}",
            )

        data = resp.json()
        choices = data.get("choices", [])
        if not choices:
            return Explanation(
                status="error",
                error_detail="No choices in API response",
            )

        text = choices[0].get("message", {}).get("content", "")
        if not text:
            return Explanation(
                status="error",
                error_detail="Empty response from model",
            )

        return Explanation(text=text, status="success")

    except requests.Timeout:
        return Explanation(status="error", error_detail="timeout")
    except requests.ConnectionError:
        return Explanation(status="error", error_detail="network_error")
    except Exception as e:
        return Explanation(status="error", error_detail=f"{type(e).__name__}: {e}")
