"""Domain models.

Pure data structures with no I/O and no dependency on other DrugForge layers.
Every user-facing result carries an explicit in-silico disclaimer.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field

IN_SILICO_DISCLAIMER = (
    "In-silico prediction only. Not clinical evidence. "
    "Laboratory validation is required."
)

ADMET_DISCLAIMER = (
    "These are in-silico predictions based on structural rules and "
    "physicochemical models. They do not constitute toxicology data or "
    "clinical evidence. Laboratory validation is required."
)

AI_AFFINITY_DISCLAIMER = (
    "AI-predicted affinity is experimental and independent of the "
    "physics-based score. It serves as supplementary confirmation only."
)

EXPLANATION_DISCLAIMER = (
    "This explanation is generated by a language model from the computed data "
    "shown alongside it. It is a computational prediction, not clinical "
    "evidence."
)


@dataclass(frozen=True)
class DockingBox:
    """Search space for docking, in Angstroms."""

    center_x: float
    center_y: float
    center_z: float
    size_x: float
    size_y: float
    size_z: float

    @property
    def center(self) -> list[float]:
        return [self.center_x, self.center_y, self.center_z]

    @property
    def size(self) -> list[float]:
        return [self.size_x, self.size_y, self.size_z]


@dataclass(frozen=True)
class ReferenceDrug:
    """Known active used as the comparison baseline for a target."""

    name: str
    smiles: str


@dataclass(frozen=True)
class Target:
    """A validated disease protein target."""

    id: str
    name: str
    disease: str
    pdb_id: str
    box: DockingBox
    reference: ReferenceDrug


@dataclass
class DockingResult:
    """Output of a single Vina run. Affinities are kcal/mol, lower is better."""

    best_affinity: float
    all_affinities: list[float]
    best_pose_pdbqt: str
    best_pose_sdf: str


@dataclass
class DrugLikeness:
    """Lipinski and Veber descriptors."""

    molecular_weight: float
    logp: float
    hbd: int
    hba: int
    tpsa: float
    rotatable_bonds: int
    lipinski_violations: int

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ADMETResult:
    """Structural alerts and absorption proxies."""

    esol_logs: float
    gi_absorption: str
    pains_alerts: list[str]
    brenk_alerts: list[str]
    nih_alerts: list[str]
    reactive_groups: list[str]
    passes_filter: bool
    failure_reasons: list[str]
    disclaimer: str = field(default=ADMET_DISCLAIMER)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ConsensusResult:
    """Vina and Vinardo combined into a single ranking score."""

    vina_score: float
    vinardo_score: float
    consensus_score: float

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class Comparison:
    """One metric compared against the target's reference drug."""

    metric: str
    molecule_value: float
    reference_value: float
    delta: float
    ratio: float
    verdict: str

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class BoltzResult:
    """AI binding confirmation from the hosted Boltz-2 API."""

    predicted_affinity: float | None = None
    confidence: float | None = None
    status: str = "unavailable"
    error_detail: str | None = None
    disclaimer: str = field(default=AI_AFFINITY_DISCLAIMER)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class Explanation:
    """Plain-language interpretation grounded in the computed result."""

    text: str = ""
    status: str = "unavailable"
    error_detail: str | None = None
    disclaimer: str = field(default=EXPLANATION_DISCLAIMER)

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ScreeningResult:
    """Complete outcome of one molecule screened against one target."""

    molecule_smiles: str
    target_id: str
    affinity_kcal_mol: float
    vinardo_score: float
    consensus_score: float
    all_affinities: list[float]
    pose_sdf: str
    pose_pdbqt: str
    drug_likeness: DrugLikeness
    admet: ADMETResult
    is_hit: bool
    hit_failure_reasons: list[str]
    comparisons: list[Comparison]
    verdict: str
    boltz: BoltzResult | None = None
    explanation: Explanation | None = None
    result_id: str | None = None
    timestamp: str | None = None

    def to_dict(self) -> dict:
        return {
            "result_id": self.result_id,
            "timestamp": self.timestamp,
            "molecule_smiles": self.molecule_smiles,
            "target_id": self.target_id,
            "affinity_kcal_mol": self.affinity_kcal_mol,
            "vinardo_score": self.vinardo_score,
            "consensus_score": self.consensus_score,
            "all_affinities": self.all_affinities,
            "pose_sdf": self.pose_sdf,
            "pose_pdbqt": self.pose_pdbqt,
            "drug_likeness": self.drug_likeness.to_dict(),
            "admet": self.admet.to_dict(),
            "is_hit": self.is_hit,
            "hit_failure_reasons": self.hit_failure_reasons,
            "comparisons": [c.to_dict() for c in self.comparisons],
            "verdict": self.verdict,
            "boltz": self.boltz.to_dict() if self.boltz else None,
            "explanation": self.explanation.to_dict() if self.explanation else None,
            "disclaimer": IN_SILICO_DISCLAIMER,
        }
